image: docker:stable
  
services:
  - name: docker:stable-dind
    command: ["--insecure-registry=192.168.93.40:8080"]   

stages:
  - build
  - deploy
  
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  CI_REGISTRY: 192.168.93.40:8080
  CONTAINER_IMAGE: $CI_REGISTRY/library/go-hello-world:${CI_COMMIT_SHORT_SHA}
  KUBECONFIG: /etc/deploy/config

build:
  stage: build
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
    
deploy:
  stage: deploy
  image: d3fk/kubectl
  script:
    - kubectl version --short
    - mkdir -p /etc/deploy/
    - echo $KUBE_CONFIG |base64 -d > $KUBECONFIG
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml
